// Client-side secret generator. The page ships a small `crypto.getRandomValues`
// helper so operators can mint a sufficiently-strong value (matching
// `openssl rand -hex 32` etc.) and paste it into Cloudflare Secrets Store /
// `wrangler secret put` / GitHub Actions secrets without the value ever
// leaving the browser. Nothing on the server side touches `Math.random`
// or the generated bytes — the worker only serves static HTML.

import { renderTabs, TAB_STYLES } from "./nav-tabs";
import { PWA_HEAD_TAGS, PWA_REGISTER_SCRIPT } from "./pwa";

const PAGE_STYLES = `
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace;
    background: #0d1117;
    color: #c9d1d9;
    padding: 24px;
    max-width: 880px;
    margin: 0 auto;
    line-height: 1.5;
  }
  h1 { font-size: 20px; margin-bottom: 12px; color: #58a6ff; }
  p.lede { font-size: 13px; color: #8b949e; margin-bottom: 20px; }
  p.lede code {
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 4px;
    padding: 1px 6px;
    font-size: 12px;
  }
  .controls {
    display: grid;
    grid-template-columns: 120px 1fr;
    gap: 10px 16px;
    align-items: center;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 16px;
    margin-bottom: 16px;
  }
  .controls label {
    font-size: 13px;
    color: #8b949e;
  }
  .controls select, .controls input[type="number"] {
    background: #0d1117;
    color: #c9d1d9;
    border: 1px solid #30363d;
    border-radius: 6px;
    padding: 6px 10px;
    font: inherit;
    font-size: 13px;
    width: 200px;
  }
  .button-row {
    display: flex;
    gap: 8px;
    margin-bottom: 12px;
  }
  button {
    background: #238636;
    color: #fff;
    border: 1px solid rgba(240,246,252,0.1);
    border-radius: 6px;
    padding: 7px 14px;
    font: inherit;
    font-size: 13px;
    cursor: pointer;
  }
  button:hover { background: #2ea043; }
  button.secondary {
    background: #21262d;
    color: #c9d1d9;
  }
  button.secondary:hover { background: #30363d; }
  .output-wrap {
    position: relative;
  }
  textarea#output {
    width: 100%;
    min-height: 110px;
    background: #0d1117;
    color: #3fb950;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 12px 14px;
    font-family: ui-monospace, "SF Mono", Consolas, monospace;
    font-size: 13px;
    resize: vertical;
    word-break: break-all;
  }
  .toast {
    position: absolute;
    top: 8px;
    right: 12px;
    background: #1f6feb;
    color: #fff;
    border-radius: 6px;
    padding: 4px 10px;
    font-size: 12px;
    opacity: 0;
    transition: opacity 120ms;
    pointer-events: none;
  }
  .toast.show { opacity: 1; }
  .examples {
    margin-top: 24px;
    background: #161b22;
    border: 1px solid #30363d;
    border-radius: 8px;
    padding: 14px 16px;
    font-size: 12.5px;
    color: #8b949e;
  }
  .examples h2 {
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: #c9d1d9;
    margin-bottom: 8px;
  }
  .examples code {
    background: #0d1117;
    border: 1px solid #30363d;
    border-radius: 4px;
    padding: 1px 6px;
    color: #d2a8ff;
  }
  .footnote {
    margin-top: 18px;
    font-size: 11.5px;
    color: #6e7681;
    line-height: 1.6;
  }
`;

const CLIENT_SCRIPT = `
const $bytes = document.getElementById("bytes");
const $format = document.getElementById("format");
const $output = document.getElementById("output");
const $toast = document.getElementById("toast");

function regenerate() {
  const n = Math.max(1, Math.min(1024, parseInt($bytes.value, 10) || 32));
  const buf = new Uint8Array(n);
  crypto.getRandomValues(buf);
  $output.value = encode(buf, $format.value);
  $output.focus();
  $output.select();
}

function encode(buf, fmt) {
  if (fmt === "hex") {
    let s = "";
    for (let i = 0; i < buf.length; i++) s += buf[i].toString(16).padStart(2, "0");
    return s;
  }
  if (fmt === "base64" || fmt === "base64url") {
    let bin = "";
    for (let i = 0; i < buf.length; i++) bin += String.fromCharCode(buf[i]);
    const b64 = btoa(bin);
    return fmt === "base64url"
      ? b64.replace(/\\+/g, "-").replace(/\\//g, "_").replace(/=+$/, "")
      : b64;
  }
  if (fmt === "alnum") {
    // Rejection-sample to avoid modulo bias on 26+26+10 = 62 alphabet.
    const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let out = "";
    let i = 0;
    while (out.length < buf.length) {
      if (i >= buf.length) {
        const more = new Uint8Array(buf.length);
        crypto.getRandomValues(more);
        for (let j = 0; j < more.length; j++) buf[j] = more[j];
        i = 0;
      }
      const v = buf[i++];
      if (v < 248) out += alphabet[v % 62]; // 248 = floor(256/62)*62
    }
    return out;
  }
  return "";
}

async function copy() {
  if (!$output.value) return;
  try {
    await navigator.clipboard.writeText($output.value);
  } catch {
    $output.focus();
    $output.select();
    document.execCommand("copy");
  }
  $toast.classList.add("show");
  setTimeout(() => $toast.classList.remove("show"), 900);
}

document.getElementById("regen").addEventListener("click", regenerate);
document.getElementById("copy").addEventListener("click", copy);
$bytes.addEventListener("change", regenerate);
$format.addEventListener("change", regenerate);
regenerate();
`;

export function handleSecretGenPage(): Response {
  const html = `<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Secret Generator — CI Dashboard</title>${PWA_HEAD_TAGS}
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    ${TAB_STYLES}
    ${PAGE_STYLES}
  </style>
</head>
<body>
  ${renderTabs("secret-gen")}
  <h1>🔐 Secret Generator</h1>
  <p class="lede">
    十分なエントロピーを持つランダム値を生成する。値は <strong>ブラウザ内で
    <code>crypto.getRandomValues</code> から生成</strong>され、ネットワークには
    一切送信されない。<code>openssl rand -hex 32</code> 等のローカル CLI と
    同等の用途 (Cloudflare Secrets Store / Workers secret / GitHub Actions
    secret / cookie 鍵 等) に使える。
  </p>

  <div class="controls">
    <label for="bytes">バイト数</label>
    <input id="bytes" type="number" min="1" max="1024" value="32" step="1">
    <label for="format">出力形式</label>
    <select id="format">
      <option value="hex">hex (openssl rand -hex N と同等)</option>
      <option value="base64url">base64url (URL safe, 末尾 = なし)</option>
      <option value="base64">base64 (RFC 4648)</option>
      <option value="alnum">英数字 (A-Za-z0-9, 偏り無し再サンプリング)</option>
    </select>
  </div>

  <div class="button-row">
    <button id="regen">🎲 再生成</button>
    <button id="copy" class="secondary">📋 コピー</button>
  </div>

  <div class="output-wrap">
    <textarea id="output" readonly spellcheck="false" autocomplete="off"></textarea>
    <span id="toast" class="toast">copied</span>
  </div>

  <section class="examples">
    <h2>用途別の推奨バイト数</h2>
    <ul style="margin-left:18px">
      <li>HS256 JWT / HMAC 共有鍵: <code>32 bytes / hex</code> (=256 bit)</li>
      <li>Cookie 署名鍵 (SESSION_COOKIE_SECRET): <code>32 bytes / hex</code></li>
      <li>AES-256 暗号鍵 (SSO_ENCRYPTION_KEY): <code>32 bytes / hex</code></li>
      <li>共有 Bearer (INTERNAL_SHARED_SECRET): <code>32-48 bytes / base64url</code></li>
      <li>OAuth state nonce: <code>16 bytes / base64url</code></li>
    </ul>
  </section>

  <p class="footnote">
    生成された値は textarea にしか保持されない (history / localStorage / KV / DO
    いずれにも書き込まない)。ページを閉じれば消える。長期保管は
    Cloudflare Secrets Store または <code>wrangler secret put</code> 経由で。
  </p>

  <script>${CLIENT_SCRIPT}</script>
  <script>${PWA_REGISTER_SCRIPT}</script>
</body>
</html>`;
  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}
